### ISSUE TITLE
TODO: Рисовать цифры и буквы полей поверх или сбоку шахматной доски

### ISSUE THREAD

**Issue by Sokolovskiy01** [Sokolovskiy01/Amazon-s-Project#17]
Высвечивать номера i и j каджой колонны и стоблбца в шахматной доске для более понятных значений логов

**Comment by LiLiTS96** [comment]
![image](https://user-images.githubusercontent.com/61879517/148681197-55b05e60-d602-41b2-89c8-a4b106a9626d.png)
