### ISSUE TITLE
BUG: ошибка при последнем ходе за белых

### ISSUE THREAD

**Issue by LiLiTS96** [Sokolovskiy01/Amazon-s-Project#22]
Только в конце игры, в режиме игры с ботом , когда белые (наши) фигуры оказываются на одной территории , но возможных ходов больше нет, появляется отображение хода для одной из фигур по верх другой.
![Снимок](https://user-images.githubusercontent.com/61879517/150703223-eafb1236-2448-493a-b371-58f7dfeb47c5.PNG)

**Comment by Sokolovskiy01** [comment]
Баг не актуален
